label: Russian
pages:
    -
        label: The Black Hack
        author: Andrey Makarov
        version: '1.2'
    -
        label: Additional Things
        author: Andrey Makarov
        version: '1.0'
        filename: additional-things.md
